[package]
name = "main"
version = "1.0.0"

[addresses]
main = "8ee0eee387ba82407d851d1164e52cc04c077f1e28614b76a2104f6209808cac"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "main"
subdir = "aptos-move/framework/aptos-framework"


[dependencies.AptosTokenObjects]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-token-objects'

