[package]
name = "dfa"
version = "1.0.0"

[addresses]
dfa = "888e8e2b916326cc1e8e694204f1bf0f2f9c3a881197a117ab21b8329203f9fc"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "main"
subdir = "aptos-move/framework/aptos-framework"


[dependencies.AptosTokenObjects]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-token-objects'

